image:
  trainingImage: <training image>
  pullPolicy: IfNotPresent

  # Insert the name of your container registry pull secret #
  pullSecret: ngc-registry

  # Insert number of GPUs and nodes #
  gpuNum: 1
  nodes: training.trainer.num_nodes

# This config is used only for small datasets that have preparation scripts in NeMo-Megatron-Launcher
# TODO: make this its own stage
datasetConfig:
  # This is the same dir as cfg_data_dir + $task_specific_subdir (e.g., squad_data)
  task_data_dir: ''

  # If provided, will download this data into cfg.data_dir. Below are the supported values:
  prepare_task_name: ''  # squad || xquad

# Use only one volume type; they are mutually exclusive.
# This volume is used for data/checkpoints/results
volumes:
  nfs:
    server: null
    path: null  # path is mirrored into pod
  # Only suitable for 1 node clusters where all workers have this path mounted/available
  hostPath:
    # Path on the host
    path: null  # path is mirrored into pod
    # https://kubernetes.io/docs/concepts/storage/volumes/#hostpath-volume-types
    # Directory = errors if does not exist
    type: "Directory"
  persistentVolumeClaim:
    # This claim should be created before running
    claimName: null
    subPath: null  # path is mirrored into pod (no leading slash b/c relative to root of pvc)

trainingConfig:

  # Specify the amount of shared memory to attach to the Pods #
  shmSize: 512Gi

  # Specify the WandB API key if using WandB for logging #
  wandbKey: "nil"

  # Specify the path to the pre-training script #
  scriptPath: <Insert path to pre-training script>

  # Insert the dnsPolicy #
  dnsPolicy: "nil"

  # Specify the environment variables to set in the container #
  envVars: "nil"
